### ISSUE TITLE
Missing dependencie(s) on setup.py install

### ISSUE THREAD

**Issue by EliotBerriot** [1flow/python-ftr#4]
When installing via `pip install ftr`  on a clean virtualenv, with Python 2.7, I get the following stacktrace:

    Collecting ftr
      Using cached ftr-0.7.13.tar.gz
        No handlers could be found for logger "ftr.extractor"
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "/tmp/pip-build-GOwCJk/ftr/setup.py", line 16, in <module>
            from ftr.version import version
          File "./ftr/__init__.py", line 38, in <module>
            from process import (  # NOQA
          File "./ftr/process.py", line 33, in <module>
            import requests
        ImportError: No module named requests
        Complete output from command python setup.py egg_info:
        No handlers could be found for logger "ftr.extractor"
        
        Traceback (most recent call last):
        
          File "<string>", line 20, in <module>
        
          File "/tmp/pip-build-GOwCJk/ftr/setup.py", line 16, in <module>
        
            from ftr.version import version
        
          File "./ftr/__init__.py", line 38, in <module>
        
            from process import (  # NOQA
        
          File "./ftr/process.py", line 33, in <module>
        
            import requests
        
        ImportError: No module named requests

I think the error come from your the following line in your `setup.py` : `from ftr.version import version`;

1. Setup.py require package init
2. Package init imports other files that requires requests to be installed

**Comment by Karmak23** [comment]
Should be OK in 0.7.14. It crashes while trying to import things before they are installed from dependancies… Chicken & egg problems are my specialty.

**Comment by EliotBerriot** [comment]
Unfortunately, I get the same error with sparks now: 

Traceback (most recent call last):

      File "<string>", line 14, in <module>

      File "/home/eliotberriot/build/ftr/setup.py", line 16, in <module>

        from ftr.version import version

      File "./ftr/__init__.py", line 38, in <module>

        from process import (  # NOQA

      File "./ftr/process.py", line 43, in <module>

        from sparks.utils.http import detect_encoding_from_requests_response

    ImportError: No module named sparks.utils.http

**Comment by Karmak23** [comment]
so nice. wait for 0.7.15 ;-)
I will check other deps.

**Comment by Karmak23** [comment]
PyPI has 0.7.15 now.

**Comment by Karmak23** [comment]
there are still bugs in an empty venv. wait.

**Comment by Karmak23** [comment]
shit. the `dependency_links` in setup.py are not applied. `sparks` doesn't get installed.

**Comment by EliotBerriot** [comment]
I can run `pip install ftr` with version `0.7.15` without getting any error (but sparks is not installed).

**Comment by EliotBerriot** [comment]
I thinks it's because you miss the `#egg` argument in your url (see this [SO post](http://stackoverflow.com/questions/3472430/how-can-i-make-setuptools-install-a-package-thats-not-on-pypi)).

Maybe you also need to add `sparks` to `install_requires`.

Anyway, [dependency_links are deprecated](http://stackoverflow.com/questions/12518499/pip-ignores-dependency-links-in-setup-py), so maybe the ultimate answer to this ticket would be to release sparks on PyPi.

**Comment by Karmak23** [comment]
yep, that's what I thought but I do not have the time today. 

sparks is a bigger baby and i'm pretty sure a lot of things will break or be missing if I don't give love to the MANIFEST.

I need humanize on PyPI too, and it's an internal fork that diverged from the original and the developer didn't want my changes merged.

I will take more time for this issue ASAP.
